version: '2'

services:
  config-server:
    image: ${HARBOR_URL}/kft-lab/config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  discovery-server:
    image: ${HARBOR_URL}/kft-lab/discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    ports:
      - 8761:8761
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/

  customers-service:
    image: ${HARBOR_URL}/kft-lab/customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
      - discovery-server
    ports:
      - 8081:8081
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinicuser
      - SPRING_DATASOURCE_PASSWORD=petclinicpass

  vets-service:
    image: ${HARBOR_URL}/kft-lab/vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
      - discovery-server
    ports:
      - 8083:8083
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinicuser
      - SPRING_DATASOURCE_PASSWORD=petclinicpass

  visits-service:
    image: ${HARBOR_URL}/kft-lab/visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
      - discovery-server
    ports:
      - 8082:8082
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinicuser
      - SPRING_DATASOURCE_PASSWORD=petclinicpass

  api-gateway:
    image: ${HARBOR_URL}/kft-lab/api-gateway
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
      - discovery-server
    ports:
      - 9001:8080
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/


