version: '2'

services:
  config-server:
    image: ${HARBOR_URL}/kft-lab/config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8888/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  discovery-server:
    image: ${HARBOR_URL}/kft-lab/discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8761/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - 8761:8761

  customers-service:
    image: ${HARBOR_URL}/kft-lab/customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8081/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - 8081:8081

  vets-service:
    image: ${HARBOR_URL}/kft-lab/vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8083/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - 8083:8083

  visits-service:
    image: ${HARBOR_URL}/kft-lab/visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8082/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - 8082:8082

  api-gateway:
    image: ${HARBOR_URL}/kft-lab/api-gateway
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.254.99.54:8085/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - 8085:8080
